default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  database: test_app_development
  username: <%= ENV.fetch("DATABASE_USER", "bookuser") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "bookpass") %>

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  database: test_app_test
  username: <%= ENV.fetch("DATABASE_USER", "bookuser") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "bookpass") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
